# Generated by Django 2.2.5 on 2019-09-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(default=0)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets_try.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets_try.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ShopINProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_price_changed', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets_try.Product')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets_try.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(through='tickets_try.ShopINProduct', to='tickets_try.Product'),
        ),
    ]
