# Generated by Django 2.2.5 on 2019-09-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_try', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinproduct',
            name='Is_max_amount_changed',
            field=models.BooleanField(default=False),
        ),
    ]
