# Generated by Django 2.2.5 on 2019-10-02 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_try', '0002_shopinproduct_is_max_amount_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets_try.Shop')),
            ],
        ),
        migrations.RenameField(
            model_name='shopinproduct',
            old_name='Is_max_amount_changed',
            new_name='is_quantity_changed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='shopinproduct',
            name='max_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shopinproduct',
            name='quantity',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shopinproduct',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets_try.Product')),
                ('reservation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets_try.Reservation')),
            ],
        ),
    ]
