# Generated by Django 2.2.5 on 2019-10-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_try', '0003_auto_20191002_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopinproduct',
            old_name='Is_price_changed',
            new_name='is_price_changed',
        ),
    ]
