# Generated by Django 2.2.5 on 2019-10-07 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_try', '0005_auto_20191004_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinproduct',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
