# Generated by Django 2.2.5 on 2019-10-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_try', '0007_auto_20191007_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinproduct',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
    ]
