# Generated by Django 2.2.5 on 2019-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_try', '0008_shopinproduct_total_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
    ]
